### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by rvmsswt002**

### CODE REVIEW

**Review by DevOps-Ramavtar — APPROVED** [review]

**Review by DevOps-Ramavtar — APPROVED** [review]

**Review by rvmsswt002 — COMMENTED** [review]
sdfasdf

**Review by DevOps-Ramavtar — APPROVED** [review]
approved

**Review by rvmsswt002 — COMMENTED** [review]
Reviewed

**Review by DevOps-Ramavtar — APPROVED** [review]
Approving

**Review by DevOps-Ramavtar — COMMENTED** [review]
Reviewed

**Review by DevOps-Ramavtar — COMMENTED** [review]
Rebvied

**Pull request merged**
